### Send POST request with json body to load feed
POST https://localhost:8080/feed/cb/123
Content-Type: application/json

{
  "pref": {
    "job_type": {
      "1": 15,
      "2": 5,
      "3": 1,
      "5": 15
    },
    "salary_range": [
      80000.0,
      120000.0
    ],
    "spontaneity": 1,
    "num_jobs_done": 12
  },
  "slice": [
    {
      "job_id": 1,
      "job_type": null,
      "job_status": 0,
      "status": "public",
      "user_id": 1,
      "duration": 0,
      "code_lang": null,
      "title": "Pianist wanted",
      "position": "Pianist",
      "description": "Just for an Insta post. You need to look good though.",
      "key_skills": "none -> Just for Instagram",
      "salary": 100,
      "currency": "Euro",
      "image_url": null,
      "start_slot": "2023-03-20T00:01:00.000Z",
      "longitude": 48.0,
      "latitude": 10.0,
      "country_code": null,
      "postal_code": null,
      "city": null,
      "address": null,
      "view_count": 0,
      "created_at": "2023-03-19T20:58:26.332Z",
      "updated_at": "2023-03-19T20:58:26.332Z",
      "applications_count": 0,
      "job_notifications": "1",
      "job_value": null
    },
    {
      "job_id": 2,
      "job_type": null,
      "job_status": 0,
      "status": "public",
      "user_id": 1,
      "duration": 0,
      "code_lang": null,
      "title": "Pianist wanted",
      "position": "Pianist",
      "description": "Just for an Insta post. You need to look good though.",
      "key_skills": "none -> Just for Instagram",
      "salary": 100,
      "currency": "Euro",
      "image_url": null,
      "start_slot": "2023-03-20T00:01:00.000Z",
      "longitude": 48.0,
      "latitude": 10.0,
      "country_code": null,
      "postal_code": null,
      "city": null,
      "address": null,
      "view_count": 0,
      "created_at": "2023-03-19T20:59:36.347Z",
      "updated_at": "2023-03-19T20:59:36.347Z",
      "applications_count": 0,
      "job_notifications": "1",
      "job_value": null
    },
    {
      "job_id": 3,
      "job_type": null,
      "job_status": 0,
      "status": "public",
      "user_id": 1,
      "duration": 0,
      "code_lang": null,
      "title": "Pianist wanted",
      "position": "Pianist",
      "description": "Just for an Insta post. You need to look good though.",
      "key_skills": "none -> Just for Instagram",
      "salary": 100,
      "euro_salary": 100,
      "currency": "Euro",
      "image_url": null,
      "start_slot": "2023-03-20T00:01:00.000Z",
      "longitude": 48.0,
      "latitude": 10.0,
      "country_code": null,
      "postal_code": null,
      "city": null,
      "address": null,
      "view_count": 0,
      "created_at": "2023-03-19T21:00:06.229Z",
      "updated_at": "2023-03-19T21:00:06.229Z",
      "applications_count": 0,
      "job_notifications": "1",
      "job_value": null
    },
    {
      "job_id": 4,
      "job_type": null,
      "job_status": 0,
      "status": "public",
      "user_id": 1,
      "duration": 0,
      "code_lang": null,
      "title": "Pianist wanted",
      "position": "Pianist",
      "description": "Just for an Insta post. You need to look good though.",
      "key_skills": "none -> Just for Instagram",
      "salary": 100,
      "currency": "Euro",
      "image_url": null,
      "start_slot": "2023-03-20T00:01:00.000Z",
      "longitude": 48.0,
      "latitude": 10.0,
      "country_code": null,
      "postal_code": null,
      "city": null,
      "address": null,
      "view_count": 0,
      "created_at": "2023-03-19T21:00:45.851Z",
      "updated_at": "2023-03-19T21:00:45.851Z",
      "applications_count": 0,
      "job_notifications": "1",
      "job_value": null
    },
    {
      "job_id": 5,
      "job_type": null,
      "job_status": 0,
      "status": "public",
      "user_id": 1,
      "duration": 0,
      "code_lang": null,
      "title": "Cellist wanted",
      "position": "Cellist",
      "description": "Just for an Insta post. You need to look good though.",
      "key_skills": "none -> Just for Instagram",
      "salary": 100,
      "currency": "Euro",
      "image_url": null,
      "start_slot": "2023-03-20T00:01:00.000Z",
      "longitude": 48.0,
      "latitude": 10.0,
      "country_code": null,
      "postal_code": null,
      "city": null,
      "address": null,
      "view_count": 0,
      "created_at": "2023-03-19T21:02:55.267Z",
      "updated_at": "2023-03-19T21:02:55.267Z",
      "applications_count": 0,
      "job_notifications": "1",
      "job_value": null
    },
    {
      "job_id": 6,
      "job_type": "Retail",
      "job_status": 0,
      "status": "public",
      "user_id": 2,
      "duration": 7,
      "code_lang": null,
      "title": "adwadawdaw",
      "position": "dawdaw",
      "description": "huiawlicaucnaw",
      "key_skills": "wd",
      "salary": 787,
      "currency": "EUR",
      "image_url": null,
      "start_slot": "0001-01-01T01:01:00.000Z",
      "longitude": 1.0,
      "latitude": 1.0,
      "country_code": null,
      "postal_code": null,
      "city": null,
      "address": null,
      "view_count": 0,
      "created_at": "2023-03-19T23:11:30.187Z",
      "updated_at": "2023-03-19T23:11:30.187Z",
      "applications_count": 0,
      "job_notifications": "1",
      "job_value": null
    },
    {
      "job_id": 8,
      "job_type": "Cleaning",
      "job_status": 0,
      "status": "public",
      "user_id": 2,
      "duration": 19821,
      "code_lang": null,
      "title": "Test job",
      "position": "HA",
      "description": "39u2z8efbsj",
      "key_skills": "7291",
      "salary": 892387,
      "currency": "BTC",
      "image_url": null,
      "start_slot": "0001-01-01T01:01:00.000Z",
      "longitude": 1.0,
      "latitude": 1.0,
      "country_code": null,
      "postal_code": null,
      "city": null,
      "address": null,
      "view_count": 0,
      "created_at": "2023-03-20T14:49:43.642Z",
      "updated_at": "2023-03-20T14:49:43.642Z",
      "applications_count": 0,
      "job_notifications": "1",
      "job_value": "01010000A0E6100000000000000000F03F000000000000F03F0000000000001C40"
    }
  ]
}
